### ISSUE TITLE
Dealing with intention class names

### ISSUE THREAD

**Issue by simonwhitaker** [chriseidhof/intentions#1]
Hi Chris,

This is all good stuff, but it's got me wondering...

I like the idea of intention classes being named after their purpose (e.g. `DismissOnEnterIntention`), but that's not sustainable for intentions that implement delegate methods, since an object can have only one delegate. For example, let's say I also want to show/hide a "Submit" button depending on whether the length of the text view's content is greater than zero. I'd have to add that functionality to `DismissOnEnterIntention`, since that's the `UITextField`'s delegate, but now the class name no longer fits the purpose. It would have to be something more generic, like `TextFieldDelegate`. Urgh. Any ideas on a sane way forward there?

(As an aside; I've always struggled with this when creating a separate object to act as a delegate; the most obvious name for the class that implements the delegate is usually the name of the delegate protocol itself; e.g. "this class is a delegate for `UITextField` so I'll call it `UITextFieldDelegate`. Oh, that's the delegate protocol's name, too." I fear this might just mean that I'm Doing It Wrong. :grinning:)

**Comment by chriseidhof** [comment]
Yes =). One other way would be to have a multicast delegate, then you can have multiple delegate intentions. I'm not sure yet either how to name things appropriately... I'll have think a bit about this.
